DATA_PATH = "diabetes.csv"
TARGET_COLUMN = "Outcome"

TEST_SIZE = 0.2
RANDOM_STATE = 42
NUM_HOSPITALS = 3

STRATIFY = True
IMPUTATION_STRATEGY = "median"
ADD_MISSING_INDICATOR = False

FEATURE_SELECTION = False
FEATURE_SELECTION_K = 6