DATA_PATH = "diabetes.csv"
TARGET_COLUMN = "Outcome"

TEST_SIZE = 0.2
RANDOM_STATE = 42
NUM_HOSPITALS = 3

DATASET_DIR="dataset"
TEST_FILE="test_set.csv"
HOSPITAL_FILE_PATTERN="hospital_{}.csv"
SERVER_ADDRESS="127.0.0.1.8080"
NUM_ROUNDS=25
LOCAL_EPOCHS=2
BATCH_SIZE=32
STRATIFY = True
IMPUTATION_STRATEGY = "median"
ADD_MISSING_INDICATOR = False

FEATURE_SELECTION = False
FEATURE_SELECTION_K = 6